# Generated by Django 3.2.4 on 2021-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Anuradhapura', 'Anuradhapura'), ('Mullaitivu', 'Mullaitivu'), ('Puttalam', 'Puttalam'), ('Gampaha', 'Gampaha'), ('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Kurunegala', 'Kurunegala'), ('Colombo', 'Colombo'), ('Kegalle', 'Kegalle'), ('Trincomalee', 'Trincomalee'), ('Hambantota', 'Hambantota'), ('Kalutara', 'Kalutara'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ratnapura', 'Ratnapura'), ('Kandy', 'Kandy'), ('Galle', 'Galle'), ('Vavuniya', 'Vavuniya'), ('Mannar', 'Mannar'), ('Matara', 'Matara'), ('Polonnaruwa', 'Polonnaruwa'), ('Badulla', 'Badulla'), ('Matale', 'Matale'), ('Monaragala', 'Monaragala'), ('Ampara', 'Ampara'), ('Kilinochchi', 'Kilinochchi')], max_length=225),
        ),
    ]
