# Generated by Django 3.2.4 on 2021-06-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Monaragala', 'Monaragala'), ('Ampara', 'Ampara'), ('Anuradhapura', 'Anuradhapura'), ('Puttalam', 'Puttalam'), ('Vavuniya', 'Vavuniya'), ('Hambantota', 'Hambantota'), ('Badulla', 'Badulla'), ('Mullaitivu', 'Mullaitivu'), ('Matara', 'Matara'), ('Batticaloa', 'Batticaloa'), ('Kurunegala', 'Kurunegala'), ('Jaffna', 'Jaffna'), ('Kilinochchi', 'Kilinochchi'), ('Galle', 'Galle'), ('Polonnaruwa', 'Polonnaruwa'), ('Trincomalee', 'Trincomalee'), ('Colombo', 'Colombo'), ('Matale', 'Matale'), ('Ratnapura', 'Ratnapura'), ('Mannar', 'Mannar'), ('Kegalle', 'Kegalle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kalutara', 'Kalutara'), ('Gampaha', 'Gampaha'), ('Kandy', 'Kandy')], max_length=225),
        ),
    ]
