# Generated by Django 3.2 on 2021-04-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
