# Generated by Django 3.2.4 on 2021-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Kilinochchi', 'Kilinochchi'), ('Puttalam', 'Puttalam'), ('Hambantota', 'Hambantota'), ('Colombo', 'Colombo'), ('Vavuniya', 'Vavuniya'), ('Badulla', 'Badulla'), ('Kegalle', 'Kegalle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Gampaha', 'Gampaha'), ('Anuradhapura', 'Anuradhapura'), ('Ratnapura', 'Ratnapura'), ('Kandy', 'Kandy'), ('Mannar', 'Mannar'), ('Kurunegala', 'Kurunegala'), ('Jaffna', 'Jaffna'), ('Ampara', 'Ampara'), ('Galle', 'Galle'), ('Monaragala', 'Monaragala'), ('Matale', 'Matale'), ('Trincomalee', 'Trincomalee'), ('Matara', 'Matara'), ('Mullaitivu', 'Mullaitivu'), ('Batticaloa', 'Batticaloa'), ('Kalutara', 'Kalutara')], max_length=225),
        ),
    ]
