# Generated by Django 3.2.4 on 2021-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Mannar', 'Mannar'), ('Vavuniya', 'Vavuniya'), ('Badulla', 'Badulla'), ('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Ratnapura', 'Ratnapura'), ('Mullaitivu', 'Mullaitivu'), ('Ampara', 'Ampara'), ('Polonnaruwa', 'Polonnaruwa'), ('Matale', 'Matale'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kurunegala', 'Kurunegala'), ('Matara', 'Matara'), ('Puttalam', 'Puttalam'), ('Monaragala', 'Monaragala'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota'), ('Kandy', 'Kandy'), ('Galle', 'Galle'), ('Anuradhapura', 'Anuradhapura'), ('Kegalle', 'Kegalle'), ('Kalutara', 'Kalutara'), ('Trincomalee', 'Trincomalee'), ('Kilinochchi', 'Kilinochchi'), ('Colombo', 'Colombo')], max_length=225),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
