# Generated by Django 3.2.4 on 2021-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Gampaha', 'Gampaha'), ('Kilinochchi', 'Kilinochchi'), ('Matale', 'Matale'), ('Badulla', 'Badulla'), ('Colombo', 'Colombo'), ('Ratnapura', 'Ratnapura'), ('Mullaitivu', 'Mullaitivu'), ('Puttalam', 'Puttalam'), ('Kegalle', 'Kegalle'), ('Galle', 'Galle'), ('Jaffna', 'Jaffna'), ('Kurunegala', 'Kurunegala'), ('Trincomalee', 'Trincomalee'), ('Polonnaruwa', 'Polonnaruwa'), ('Monaragala', 'Monaragala'), ('Kalutara', 'Kalutara'), ('Vavuniya', 'Vavuniya'), ('Mannar', 'Mannar'), ('Matara', 'Matara'), ('Kandy', 'Kandy'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Batticaloa', 'Batticaloa'), ('Hambantota', 'Hambantota'), ('Anuradhapura', 'Anuradhapura'), ('Ampara', 'Ampara')], max_length=225),
        ),
    ]
