# Generated by Django 3.2.4 on 2021-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Hambantota', 'Hambantota'), ('Jaffna', 'Jaffna'), ('Vavuniya', 'Vavuniya'), ('Ampara', 'Ampara'), ('Ratnapura', 'Ratnapura'), ('Matale', 'Matale'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kalutara', 'Kalutara'), ('Kegalle', 'Kegalle'), ('Badulla', 'Badulla'), ('Trincomalee', 'Trincomalee'), ('Matara', 'Matara'), ('Anuradhapura', 'Anuradhapura'), ('Monaragala', 'Monaragala'), ('Polonnaruwa', 'Polonnaruwa'), ('Colombo', 'Colombo'), ('Kurunegala', 'Kurunegala'), ('Mullaitivu', 'Mullaitivu'), ('Kandy', 'Kandy'), ('Puttalam', 'Puttalam'), ('Gampaha', 'Gampaha'), ('Galle', 'Galle'), ('Kilinochchi', 'Kilinochchi'), ('Mannar', 'Mannar'), ('Batticaloa', 'Batticaloa')], max_length=225),
        ),
    ]
