# Generated by Django 3.2.4 on 2021-07-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Matale', 'Matale'), ('Kalutara', 'Kalutara'), ('Kilinochchi', 'Kilinochchi'), ('Puttalam', 'Puttalam'), ('Kurunegala', 'Kurunegala'), ('Matara', 'Matara'), ('Gampaha', 'Gampaha'), ('Vavuniya', 'Vavuniya'), ('Batticaloa', 'Batticaloa'), ('Galle', 'Galle'), ('Mannar', 'Mannar'), ('Badulla', 'Badulla'), ('Ratnapura', 'Ratnapura'), ('Polonnaruwa', 'Polonnaruwa'), ('Mullaitivu', 'Mullaitivu'), ('Hambantota', 'Hambantota'), ('Trincomalee', 'Trincomalee'), ('Anuradhapura', 'Anuradhapura'), ('Colombo', 'Colombo'), ('Kegalle', 'Kegalle'), ('Kandy', 'Kandy'), ('Jaffna', 'Jaffna'), ('Monaragala', 'Monaragala')], max_length=225),
        ),
    ]
