# Generated by Django 3.2.4 on 2021-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Matara', 'Matara'), ('Puttalam', 'Puttalam'), ('Vavuniya', 'Vavuniya'), ('Hambantota', 'Hambantota'), ('Kandy', 'Kandy'), ('Kurunegala', 'Kurunegala'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Mullaitivu', 'Mullaitivu'), ('Kalutara', 'Kalutara'), ('Gampaha', 'Gampaha'), ('Ratnapura', 'Ratnapura'), ('Monaragala', 'Monaragala'), ('Batticaloa', 'Batticaloa'), ('Anuradhapura', 'Anuradhapura'), ('Jaffna', 'Jaffna'), ('Badulla', 'Badulla'), ('Colombo', 'Colombo'), ('Mannar', 'Mannar'), ('Trincomalee', 'Trincomalee'), ('Matale', 'Matale'), ('Kilinochchi', 'Kilinochchi'), ('Kegalle', 'Kegalle')], max_length=225),
        ),
    ]
