# Generated by Django 3.2.5 on 2021-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Gampaha', 'Gampaha'), ('Monaragala', 'Monaragala'), ('Hambantota', 'Hambantota'), ('Mullaitivu', 'Mullaitivu'), ('Mannar', 'Mannar'), ('Vavuniya', 'Vavuniya'), ('Ampara', 'Ampara'), ('Puttalam', 'Puttalam'), ('Batticaloa', 'Batticaloa'), ('Kalutara', 'Kalutara'), ('Polonnaruwa', 'Polonnaruwa'), ('Jaffna', 'Jaffna'), ('Galle', 'Galle'), ('Kandy', 'Kandy'), ('Kurunegala', 'Kurunegala'), ('Badulla', 'Badulla'), ('Colombo', 'Colombo'), ('Kegalle', 'Kegalle'), ('Anuradhapura', 'Anuradhapura'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Trincomalee', 'Trincomalee'), ('Matale', 'Matale'), ('Ratnapura', 'Ratnapura'), ('Matara', 'Matara'), ('Kilinochchi', 'Kilinochchi')], max_length=225),
        ),
    ]
