# Generated by Django 3.2.5 on 2021-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Monaragala', 'Monaragala'), ('Ampara', 'Ampara'), ('Vavuniya', 'Vavuniya'), ('Hambantota', 'Hambantota'), ('Batticaloa', 'Batticaloa'), ('Kalutara', 'Kalutara'), ('Ratnapura', 'Ratnapura'), ('Mannar', 'Mannar'), ('Matara', 'Matara'), ('Jaffna', 'Jaffna'), ('Mullaitivu', 'Mullaitivu'), ('Anuradhapura', 'Anuradhapura'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kilinochchi', 'Kilinochchi'), ('Matale', 'Matale'), ('Galle', 'Galle'), ('Badulla', 'Badulla'), ('Puttalam', 'Puttalam'), ('Gampaha', 'Gampaha'), ('Trincomalee', 'Trincomalee'), ('Kurunegala', 'Kurunegala'), ('Polonnaruwa', 'Polonnaruwa'), ('Kegalle', 'Kegalle'), ('Kandy', 'Kandy'), ('Colombo', 'Colombo')], max_length=225),
        ),
    ]
