# Generated by Django 3.2.4 on 2021-07-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('suv', 'Suv/Jeep'), ('bike', 'Motorbike'), ('bus', 'Bus'), ('tuk', 'Three Wheeler'), ('heavy', 'Heavy Vehicle')], default='car', max_length=10)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], default='new', max_length=5)),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=10)),
                ('engine_capacity', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('semi', 'semi-automatic')], default='manual', max_length=7)),
                ('description', models.TextField(null=True)),
                ('front', models.ImageField(upload_to='')),
                ('back', models.ImageField(upload_to='')),
                ('interior', models.ImageField(upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
