# Generated by Django 3.2.4 on 2021-07-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210715_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='back',
            field=models.ImageField(upload_to='back/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front',
            field=models.ImageField(upload_to='front/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='interior',
            field=models.ImageField(upload_to='interior/'),
        ),
    ]
