# Generated by Django 3.2.4 on 2021-07-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210716_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='back',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='interior',
        ),
    ]
