# Generated by Django 3.2.4 on 2021-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20210716_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='back',
            field=models.ImageField(blank=True, upload_to='back/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior',
            field=models.ImageField(blank=True, upload_to='interior/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front',
            field=models.ImageField(blank=True, upload_to='front/'),
        ),
    ]
