# Generated by Django 3.2.5 on 2021-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20210716_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='back',
            field=models.ImageField(upload_to='back/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front',
            field=models.ImageField(upload_to='front/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='interior',
            field=models.ImageField(upload_to='interior/'),
        ),
    ]
